### PR TITLE
Update es test version to 5.2

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by XWB** [comment]
@ruflin Any ETA on the next release? It would be nice to a release containing https://github.com/ruflin/Elastica/commit/3e029374bbb052c45b24accc75f3941b5a4935dc

**Comment by ruflin** [comment]
No ETA but definitively something I can push forward :-) Put it on my TODO list.

**Comment by XWB** [comment]
> Put it on my TODO list.

Excellent :)

**Comment by ruflin** [comment]
@XWB I assume you saw https://github.com/ruflin/Elastica/releases/tag/5.2.0

**Comment by XWB** [comment]
Yes, already installed :) Thanks!

**Comment by XWB** [comment]
@ruflin 

All `FOSElasticaBundle` [resetter tests](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Tests/Index/ResetterTest.php) fail after upgrading Elastica to 5.2, any idea where I should start [looking](https://github.com/ruflin/Elastica/compare/5.1.0...5.2.0)?

**Comment by ruflin** [comment]
Could you share the CI error you get? What is resetter doing?

**Comment by XWB** [comment]
@ruflin 

1) FOS\ElasticaBundle\Tests\Index\ResetterTest::testResetAllIndexes
Expectation failed for method name is equal to <string:request> when invoked 2 time(s).
Method was expected to be called 2 times, actually called 0 times.

2) FOS\ElasticaBundle\Tests\Index\ResetterTest::testResetIndex
Expectation failed for method name is equal to <string:request> when invoked 2 time(s).
Method was expected to be called 2 times, actually called 0 times.

3) FOS\ElasticaBundle\Tests\Index\ResetterTest::testResetIndexWithDifferentName
Expectation failed for method name is equal to <string:request> when invoked 2 time(s).
Method was expected to be called 2 times, actually called 0 times.

4) FOS\ElasticaBundle\Tests\Index\ResetterTest::testResetIndexWithDifferentNameAndAlias
Expectation failed for method name is equal to <string:request> when invoked 2 time(s).
Method was expected to be called 2 times, actually called 0 times.

5) FOS\ElasticaBundle\Tests\Index\ResetterTest::testResetType
Expectation failed for method name is equal to <string:request> when invoked 3 time(s).
Method was expected to be called 3 times, actually called 0 times.

6) FOS\ElasticaBundle\Tests\Index\ResetterTest::testResetTypeWithChangedSettings
Expectation failed for method name is equal to <string:request> when invoked 3 time(s).
Method was expected to be called 3 times, actually called 0 times.

**Comment by ruflin** [comment]
Could this be related to https://github.com/ruflin/Elastica/pull/1277 ?

**Comment by XWB** [comment]
I think so, but I have no clue where to start looking.

**Comment by ruflin** [comment]
I think the problem is that you check for `request` calls but now `requestEndpoint` is called. TBH this kind of test is quite new to me :-)

**Comment by XWB** [comment]
Found it, thanks :)

https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/f434157b69cd93d3d94edef6ab9a073ee295d031

**Pull request merged**
