### PR TITLE
Fix IDE doc for better auto-completion

### PR DESCRIPTION
**Pull request by bakura10**
On modern IDE (at least on PHPStorm), returning static allows to let the IDE resolve on real-time based on the caller type. This is necessary if we still want to have nice autocompletion with the fluent interface. I've only fixed that for param and aggregations, I'll do another PR in the future if I find other cases :)

### CODE REVIEW

**Comment by im-denisenko** [comment]
I always thought that `@return static` or `@return self` should be used for static methods like Elastica\Search::create, but in case of fluent interface `@return $this` is more semantic, isn't it? This differences also described in proposed [psr-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#keyword) (13, 14, 15).

// my ST3 cannot into autocomplete, so maybe i'm just wrong :)

**Comment by bakura10** [comment]
I just tried and I can confirm that $this work as well :). I like static because it is coherent with how late-state binding works, but I'm open to change that to $this. Let's let @ruflin decide :D.

**Comment by ruflin** [comment]
I wasn't even aware that PHPStorm is now able to use static or $this for auto complete. I quite like "$this" as it describes very well what it actually is. In which IDE's is this going to work?

**Comment by bakura10** [comment]
I'm pretty sure NetBeans take advantage of that!

**Comment by im-denisenko** [comment]
Eclipse confirmed also

**Comment by bakura10** [comment]
I've updated to modify static to $this!

**Comment by ruflin** [comment]
Merged. Thx.

**Pull request merged**
