### PR TITLE
Add support for specifying a pipeline when indexing documents

### PR DESCRIPTION
**Pull request by stof**
this is #1455 cherry-picked on 5.x

### CODE REVIEW

**Comment by ruflin** [comment]
There seems to be an error on travis:
```
1) Elastica\Test\ClientTest::testAddDocumentsPipeline
Failed asserting that an array has the key 'new'.

```

**Comment by stof** [comment]
OK, understood: Elastica 5.x does not support the second argument of `Type::addDocuments`, and so won't support pipelines for the bulk API through this argument.

**Comment by ruflin** [comment]
Hm, I see. Would it make sense to also backport this feature?

**Comment by stof** [comment]
your choice.

**Comment by ruflin** [comment]
My normally approach here is if someone asks for it, I'm +1 on it and ask for the contribution 😇

**Comment by deguif** [comment]
Closing as `5.x` branch is not maintained anymore.

**Pull request closed without merging**
