### PR TITLE
update global filter aggregation method

### PR DESCRIPTION
**Pull request by oguzhanT**
added filter to GlobalAggregation 

`"total": {
  "global": {},
  "aggs": {
    "all": {
      "filter": {
        "bool": {
          "must": [
            {
              "term": {
                "cityId": 1
              }
            }
          ]
        }
      }
    }
  }
}`

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for the contribution .This seems to break the tests, could you take a look?

Could you also add some tests for the change and update the PR description with a few more details?

And could you add a changelog entry?

**Comment by oguzhanT** [comment]
i didn't understand why the cs linter is failed. Maybe can u check it

**Comment by ruflin** [comment]
Best run `make lint` on your machine and it should fix it for you.

**Comment by ruflin** [comment]
BTW now the linting passes but all tests fail :-)

**Comment by ruflin** [comment]
Overall LGTM. Any chance you could add an integration test for it?

**Comment by ruflin** [comment]
You should probably rebase your PR on master to get the most recent changes in. Also somehow it still breaks the tests.

**Comment by ruflin** [comment]
I restarted CI as not sure if the tests were just flaky. I see you rebased on master on June 21. (or I think it was master ;-) ). Perhaps do that again to see what happens with the CI?

**Comment by deguif** [comment]
Duplicate with https://github.com/ruflin/Elastica/pull/1630
@oguzhanT Closing as this seems achievable with this code (unless I'm missing something).

```php

use Elastica\Aggregation\Filter;
use Elastica\Aggregation\GlobalAggregation;
use Elastica\Query;

$globalAggregation = (new GlobalAggregation('global'))
    ->addAggregation(new Filter('all', (new Query\BoolQuery())
        ->addMust((new Query\Term())->setTerm('cityId', 1))
    ))
```

Feel free to reopen if that's not the case.

**Pull request closed without merging**
