### PR TITLE
Update Xdebug to v2.7.2

### PR DESCRIPTION
**Pull request by jdreesen**
Updated to Xdebug to v2.7.3 in PHP 7.0, 7.1, 7.2 and 7.3

### CODE REVIEW

**Comment by p365labs** [comment]
@jdreesen I think u need to rebase

**Comment by jdreesen** [comment]
Done

**Comment by p365labs** [comment]
tnx a lot @jdreesen !

**Comment by ruflin** [comment]
Thanks for the PR @jdreesen and @p365labs for merging!

**Pull request merged**
