### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by pborreli**

### CODE REVIEW

**Comment by ruflin** [comment]
@pborreli These files are automatically generated from the repo here: https://github.com/ruflin/Elastica.io Means the fix has to be pushed here. Are you going to open a pull request here or should I fix it? Thx for info about the typo anyways.

**Comment by ruflin** [comment]
I just fixed it here and pushed it online: https://github.com/ruflin/Elastica.io/commit/c4bcb7d927d27962adca4cdedcf5e8cfccc2ae19

**Comment by pborreli** [comment]
you should put a CONTRIBUTING.md file to explain that kind of strange things :wink:

**Comment by ruflin** [comment]
Second paragraph here? ;-) http://elastica.io/

**Comment by pborreli** [comment]
https://github.com/blog/1184-contributing-guidelines

**Comment by ruflin** [comment]
@pborreli Nice, didn't know about this one. Do you have time to open a pull request with this one?

**Pull request closed without merging**
