### PR TITLE
Use new ingest pipeline endpoint classes

### PR DESCRIPTION
**Pull request by deguif**
See previous (old) PR on official elasticsearch library: https://github.com/elastic/elasticsearch-php/pull/968
This is to prepare support for version 8.x

### CODE REVIEW

**Review by ruflin — APPROVED** [review]

**Comment by deguif** [comment]
Merging even if failed, as failure is due to a 403 when downloading `php-cs-fixer` on a job that doesn't need it.

**Comment by ruflin** [comment]
@deguif Please do not merge on red CI even if you assume it is not related. We rather rerun CI. Happy to give you access to do that.

**Comment by deguif** [comment]
@ruflin sorry about that, I will not merge next time when it's red.
Instead I will trigger another build by amending last commit.

**Comment by ruflin** [comment]
@deguif An other option is to get you trigger permissions on the Travis build so you can retrigger it in the UI. Can you check if you already have access there because you are a contributor? If not, let me figure out how I can give you access.

**Pull request merged**
