### PR TITLE
delete type is deprecated

### PR DESCRIPTION
**Pull request by ewgRa**
PR that deprecate delete type according to https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-delete-mapping.html

### CODE REVIEW

**Comment by ewgRa** [comment]
One moment, will add to changelog

**Comment by ewgRa** [comment]
done

**Comment by ruflin** [comment]
LGTM. Waiting for travis to complete.

**Comment by ruflin** [comment]
Merged. Thx.

**Pull request merged**
