### PR TITLE
'average' => 'avg'

### PR DESCRIPTION
**Pull request by Raffaello**
see here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

### CODE REVIEW

**Comment by ruflin** [comment]
Can you update the CHANGELOG.md file?

**Comment by Raffaello** [comment]
Yes of course!

I am not sure what I have to write into it..

create a new paragraph for v 2.3.2 would it be ok?

**Comment by ruflin** [comment]
Just put it here under Unrelease: https://github.com/ruflin/Elastica/blob/master/CHANGELOG.md Best is to add it to this PR.

**Comment by ruflin** [comment]
@Raffaello I finally merged this. Sorry for the delay, somehow I was distracted by the 3.0.0 release :-)

**Pull request merged**
