### PR TITLE
Implement Countable on Objects

### PR DESCRIPTION
**Pull request by mgallego**
Implements Countable interface in objects to run Elastica 3.x with PHP7.2 version.

Based on PR. https://github.com/ruflin/Elastica/pull/1378

**This is a WIP PR because the tests fails on local without changing code and I need to test through Travis**

The test errors are of kind "Elastica\Exception\ResponseException: all shards failed" and not alwais fails

### CODE REVIEW

**Comment by mgallego** [comment]
I thought that the PR must launch Travis. So please check the PR to integrate it.

**Comment by ruflin** [comment]
The problem lies here: https://github.com/ruflin/Elastica/blob/3.x/.travis.yml#L8 Previous builds were always on master. Could you open an additional PR against 3.x to add 3.x branch to the list?

**Comment by p365labs** [comment]
@mgallego have a look at #1572

**Comment by mgallego** [comment]
I don't understand the reason why codecov fails, but I cannot see new executions and I guess is because the configuration of dovecot.

I created a new PR with dovecot config based on master branch https://github.com/ruflin/Elastica/pull/1578 but I dont know if this is the solution.

What is the conflict between my PR and dovecot, I don't know anything about covecot service.

**Comment by ruflin** [comment]
@mgallego I'm ok to ignore codecov on PR's against this branch.

**Comment by senechaux** [comment]
> @mgallego I'm ok to ignore codecov on PR's against this branch.

@ruflin So is it going to be merged?

**Comment by ruflin** [comment]
Did you see the PR review from @p365labs https://github.com/ruflin/Elastica/commit/435fbf41bb166cbb73c44962417138d2d3df1454#r31731591 ? Not sure if you addressed this. Probably got lost as it was a comment on the commit.

**Comment by mgallego** [comment]
> Did you see the PR review from @p365labs [435fbf4#r31731591](https://github.com/ruflin/Elastica/commit/435fbf41bb166cbb73c44962417138d2d3df1454#r31731591) ? Not sure if you addressed this. Probably got lost as it was a comment on the commit.

I removed the code, because was innecesary. I copied it from referrer PR triying to avoid the codecov block.

But I think that is mergeable now

**Comment by p365labs** [comment]
@ruflin @mgallego 👍 mergeable 4 me!

**Comment by mgallego** [comment]
Thanks

**Pull request merged**
