### PR TITLE
Fix codecov accuracy

### PR DESCRIPTION
**Pull request by JustinHook**

### CODE REVIEW

**Comment by ruflin** [comment]
@JustinHook The main reason we had the previous option was that first all unit tests run (which is fasted) and then the integrationt tests etc. So it was very easy to spot which parts were failing. But there is an issue with the above as it sometimes reports green when it should be red.

How does this change the codecov accuracy?

**Comment by JustinHook** [comment]
It seems like codecov has an issue with multiple coverage reports.
The coverage of Elastica\Rescore\Query.php is 92.59% [1] with this change compared to 80.64% [2] from master.
I also think that if the build is showing as green in github then it shouldn't require someone to double check in travis that there was infact no errors in any of the builds.

[1] https://codecov.io/github/ruflin/Elastica/lib/Elastica/Rescore/Query.php?ref=601af3af5694a533de829b18c78d072c9fc44477
[2] https://codecov.io/github/ruflin/Elastica/lib/Elastica/Rescore/Query.php?ref=57b9da5bcc08d73a97920b32b1995f8f3af7413a

On a separate note, it looks like the test `Elastica\Test\StatusTest::testIndexExists` is inconsistently passing/failing. Both these builds are against the same commit https://travis-ci.org/ruflin/Elastica/builds/95094404 and https://travis-ci.org/ruflin/Elastica/builds/95090736

**Comment by ruflin** [comment]
The best person to ask why this difference exist is probably @stevepeak (see comment above).

I would still prefer to have all three builds separate if somehow possible. Of course, having it green here and the build failed is not an option. Do you see an option to keep the three builds but have these requirements met?

About the flacky test: Yes we should look into this why the test is flaky. Not sure if it is related to the update to ES 2.0.0 as before I think we finally got the tests stable.

**Comment by stevepeak** [comment]
Hey @JustinHook and @ruflin the coverage changes are due to our report fixes to increase report accuracy. Comparing the two reports you will notice that brackets are no longer included.

Simply:
```diff
+ } # before
- } # after
```
You can read more here: https://github.com/codecov/support/wiki/Report-Fixes

**Comment by ruflin** [comment]
@stevepeak That means sending on report or multiple should not matter, right?

**Comment by stevepeak** [comment]
I can review the uploads to confirm, but the difference between these reports is the extra `}` brackets being measured. Which there seems to be a couple more (L38, L24) that need to be removed as well. These fixes are a work in progress.

Thanks!

**Comment by ruflin** [comment]
@stevepeak I take your answer as: It should work and we should resend the reports now to see if it works. If not, I will mention you again. Ok?

**Comment by ruflin** [comment]
@JustinHook Sorry for closing, clicked the wrong button ... Reopened it again.

**Comment by JustinHook** [comment]
@ruflin are you able to manually trigger a codecov build against master to see if it handles multiple reports any better now?

**Comment by ruflin** [comment]
@JustinHook I just restarted to the master travis build which should send a new report to codecov: https://travis-ci.org/ruflin/Elastica/builds/94437264

**Comment by stevepeak** [comment]
> I take your answer as: It should work and we should resend the reports now to see if it works. If not, I will mention you again. Ok?

Yes, Feel free to mention me anytime.

**Comment by JustinHook** [comment]
@ruflin can you kill this build, it seems to have got stuck https://travis-ci.org/ruflin/Elastica/builds/95446866

**Comment by ruflin** [comment]
Stopped and started it again. I assume it is related to the issues travis had in the last 24h

**Comment by JustinHook** [comment]
@ruflin they still seem stuck
* https://travis-ci.org/ruflin/Elastica/builds/95560594
* https://travis-ci.org/ruflin/Elastica/builds/95446866

**Comment by ruflin** [comment]
@JustinHook Seems like travis is messing with me today. Just sent them a message again to have a look.

**Comment by ruflin** [comment]
@JustinHook @travis-ci is going to have a look. Lets see what magic they will come up with.

**Comment by ruflin** [comment]
@JustinHook Builds should now be green again.

**Comment by JustinHook** [comment]
@stevepeak codecov has been run again but this time producing 3 coverage xml files. It doesn't seem like it combines the reports together as the *# of hits* is lower

1 coverage file = https://codecov.io/github/ruflin/Elastica/lib/Elastica/Rescore/Query.php?ref=601af3af5694a533de829b18c78d072c9fc44477

3 coverage files = https://codecov.io/github/ruflin/Elastica/lib/Elastica/Rescore/Query.php?ref=dcabb132ad8cce96b6ce31d278515e2ce23cf0c8

**Comment by stevepeak** [comment]
@JustinHook these commits appear to not exist in GitHub. But the difference is likely due to the line adjustments I spoke of earlier. Do you have other recent commits that I can check?

**Comment by ruflin** [comment]
@JustinHook Any updates here?

**Comment by JustinHook** [comment]
@stevepeak it still doesn't appear correct.

**3 separate coverage xml reports = 80.64%**
https://codecov.io/github/ruflin/Elastica/lib/Elastica/Rescore/Query.php?ref=2b4eb2c1731c7c2d8f4dbc5e5b08818dd4f6c3ce

**1 coverage xml report = 92.59**
https://codecov.io/github/ruflin/Elastica/lib/Elastica/Rescore/Query.php?ref=19aa1e23ed5424469e6a99fb2e483b20e59c3ccb

**Comment by stevepeak** [comment]
I'll review the uploads and report back. Thanks for the commits. I'll be
back online later.

**Comment by ruflin** [comment]
@JustinHook @stevepeak Thanks for looking into this one.

**Comment by stevepeak** [comment]
The difference are these strange lines like [64 here](https://codecov.io/github/ruflin/Elastica/lib/Elastica/Rescore/Query.php?ref=2b4eb2c1731c7c2d8f4dbc5e5b08818dd4f6c3ce#l-64) 

We try to fix issues like these, [as seen here](https://github.com/codecov/codecov-bash/blob/ad3f2f5b548dbf16685fbaaf1954e75c9706ab0d/codecov#L655-L656).

I looks like my method here is not properly finding the fixes. I'll need to make adjustments to the bash uploader to fix this. In this commit: https://github.com/codecov/codecov-bash/commit/bf76161cd12f869be742e27bc00d7f570d663a37

------

However, with all this being sad. The question remains: why was line 64 not covered? If you review the reports below you will find that Codecov is reporting properly. The commit 2b4eb2c indeed expresses line 64 as not covered (keep in mind that I am aware of this issue with php coverage reports and have adjusted our process to fix these issues above).

```
Fri Jan 08 09:30:48 UTC 2016 : INFO, {"commit": "2b4eb2c", "id": "5fc05f92-16f3-4feb-ac49-0f7a25250aa3", "method": "POST", "ms": "254", "reason": "OK", "reportid": "upload:131927:2b4eb2c1731c7c2d8f4dbc5e5b08818dd4f6c3ce:2024.3:2279:1452245448.46", "service": "github", "size": 0.0, "slug": "ruflin/Elastica", "speed": 14, "status": 200, "url": "/upload/v3?package=bash-5ca7b8c&branch=master&commit=2b4eb2c1731c7c2d8f4dbc5e5b08818dd4f6c3ce&build=2024.3&build_url=&slug=ruflin/Elastica&service=travis-org&pr=false&job=101017757"} 200 Context


Sun Jan 10 21:18:19 UTC 2016 : INFO, {"commit": "19aa1e2", "id": "980f3520-c2bb-4e2b-bda0-91bc9873323e", "method": "POST", "ms": "222", "reason": "OK", "reportid": "upload:131927:19aa1e23ed5424469e6a99fb2e483b20e59c3ccb:2025.3:7203:1452460699.96", "service": "github", "size": 0.0, "slug": "ruflin/Elastica", "speed": 10, "status": 200, "url": "/upload/v3?package=bash-5ca7b8c&branch=master&commit=19aa1e23ed5424469e6a99fb2e483b20e59c3ccb&build=2025.3&build_url=&slug=ruflin/Elastica&service=travis-org&pr=1002&job=101462751"} 200 Context
```

- Raw upload for [2b4eb2c]( https://codecov.s3.amazonaws.com/repos/EC55CECE92D7A61E808BB6F114878128/uploads/upload:131927:2b4eb2c1731c7c2d8f4dbc5e5b08818dd4f6c3ce:2024.3:2279:1452245448.46.txt)
- Raw upload for [19aa1e2](https://codecov.s3.amazonaws.com/repos/EC55CECE92D7A61E808BB6F114878128/uploads/upload:131927:19aa1e23ed5424469e6a99fb2e483b20e59c3ccb:2025.3:7203:1452460699.96.txt)

> PS access to these raw uploads  and logs are in our next major release

**Comment by ruflin** [comment]
@JustinHook @stevepeak Thanks for all the discussions and insights. I haven't checked in detail if the above is still an issue but I think for combining coverage report fixes should be done on the codecov side.

@JustinHook You mentioned earlier about PR's which are green but failed. Is this still happening. I hoped we have solved this with the EXIT_STATUS variable.

I'm closing this PR. That doesn't mean we can't reopen the PR and I'm happy to continue the discussion.

**Pull request closed without merging**
