### PR TITLE
fix(queryBuilder): compatibility with elasticsearch 2.x

### PR DESCRIPTION
**Pull request by piwii**

### CODE REVIEW

**Comment by ErikSaunier** [comment]
👍

**Comment by ruflin** [comment]
Thanks for the update. LGTM

**Comment by piwii** [comment]
your welcome, is it possible to create a new tag ? @ruflin

**Comment by ruflin** [comment]
Here you go: http://elastica.io/2016/09/23/release-3-dot-2-3/

**Pull request merged**
