### PR TITLE
merge two condition to one

### PR DESCRIPTION
**Pull request by ReenExe**

### CODE REVIEW

**Comment by merk** [comment]
To me this doesn't increase the readability of the code, and to me that is more important than the conciseness.

**Comment by ruflin** [comment]
@merk @ReenExe I think that is a general question and also often is personal taste. I support here the opinion of @merk. Code should be like a book to read.

**Comment by ReenExe** [comment]
@ruflin, my variant shorter - so what do? Close or merge?

**Comment by ruflin** [comment]
@ReenExe Will close it. Thanks for looking into it anyways.

**Pull request closed without merging**
