### PR TITLE
Fixing MoreLikeThis query on non-indexed documents

### PR DESCRIPTION
**Pull request by sebesvn**

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for the PR. Two things:
* Could you update the CHANGELOG.md file?
* Should we add an integration test to make sure it also works with elasticsearch?

**Comment by sebesvn** [comment]
1. I've updated the Changelog.
2. I guess you sure can add an integration test in Travis.

**Comment by ruflin** [comment]
Thanks for the Changelog. We already have quite a few functional (sorry, used integration before) tests which you can copy paste and adjust to your need: https://github.com/sebesvn/Elastica/blob/master/test/lib/Elastica/Test/Query/MoreLikeThisTest.php#L61 No magic needed. All connection stuff etc. is already done.

**Comment by sebesvn** [comment]
Sorry I misunderstood what you meant about these integration tests :)
It's pushed now.

**Comment by ruflin** [comment]
Merged. Thanks a lot for getting this in. I think I should a new release soonish :-)

**Comment by sebesvn** [comment]
Awesome :)

**Pull request merged**
