### PR TITLE
Update php-cs-fixer to 2.16.7

### PR DESCRIPTION
**Pull request by deguif**

### CODE REVIEW

**Review by ruflin — APPROVED** [review]
LGTM especially as the Code checker is run on Github Actions and is green ;-)

**Comment by ruflin** [comment]
@deguif BTW any chance you could contribute an additional github action to at least have CI running on a single PHP version at the moment so our PR's get tested?

**Comment by deguif** [comment]
I'm working on it for the unit part excluding functional tests: https://github.com/deguif/Elastica/actions/runs/394133888

**Comment by ruflin** [comment]
++ on excluding the functional tests for now to get it running quickly. I'm wondering if these should become 2 stages anyway. Like all the unit tests run first across all environments and only if these pass, the functional tests are run 🤔

**Comment by deguif** [comment]
I'm adding a changelog and I will merge it

**Pull request merged**
