### PR TITLE
update docker config in order to fix docker version

### PR DESCRIPTION
**Pull request by p365labs**
This PR try to solve the problem I show on issue #1406

### CODE REVIEW

**Comment by ruflin** [comment]
@p365labs Argh, sorry. Just saw this one too late after doing https://github.com/ruflin/Elastica/pull/1409. But I think yours is nicer, could you rebase?

**Comment by p365labs** [comment]
@ruflin done . :)

**Comment by p365labs** [comment]
I made an error.... I closed it can u reopen it or I just need to create a new PR?

**Comment by ruflin** [comment]
Strangely I don't see a reopen button. Did you delete the branch? Just open a new PR :-)

**Comment by p365labs** [comment]
done [PR #1410](https://github.com/ruflin/Elastica/pull/1410)

**Pull request closed without merging**
