### PR TITLE
Prepare release 7.2.0

### PR DESCRIPTION
**Pull request by thePanz**
I am not 100% sure about the BC breaks, as they would call for a major release

Any inputs @deguif ?

### CODE REVIEW

**Comment by franmomu** [comment]
For the BC breaks introduced see https://github.com/ruflin/Elastica/pull/2082#discussion_r903405419 and https://github.com/ruflin/Elastica/pull/2082#issuecomment-1163082427, they are in classes not likely to be extended and it was to fix some behaviour.

**Review by deguif — APPROVED** [review]
There is a BC break as pointed in the comment, but its impact should be limited.

**Comment by deguif** [comment]
@thePanz there are some deprecations to update. For example in this PR (https://github.com/ruflin/Elastica/pull/2070/files) it was marked as introduced in 7.1.6 but should be 7.2.0.

**Comment by thePanz** [comment]
@deguif I rebased this PR to the latest changes

Thanks @franmomu for the PR fixing the deprecation messages with the correct version

**Comment by thePanz** [comment]
Merged, and v7.2.0 released

**Pull request merged**
