### PR TITLE
Added setMinDocCount and setExtendedBounds options

### PR DESCRIPTION
**Pull request by markeilander**

### CODE REVIEW

**Comment by ruflin** [comment]
@markeilander I'm not sure if this change is as you intended it. You rewrote a test file and are overwriting the old test file with a specific implementation as far as I can see. I don't think that was your intention.

**Comment by markeilander** [comment]
I havend't touched any test files....

I'm not sure what went wrong, i wanted to add 2 functions to Elastica/lib/Elastica/Aggregation/DateHistogram.php

Does your build proces write testcases for this kind of changes?

**Comment by ruflin** [comment]
@markeilander There is no automatic code generation. It looks like you just changed the wrong file :-) See here: https://github.com/ruflin/Elastica/pull/943/files You added your new functions to test/lib/Elastica/Test/Aggregation/DateHistogramTest.php instead of lib/Elastica/lib/Elastica/Aggregation/DateHistogram.php

**Comment by markeilander** [comment]
Aaaaaah i see.... my bad.. i will fix this asap.

**Comment by markeilander** [comment]
Done -> https://github.com/ruflin/Elastica/pull/947

**Pull request closed without merging**
