### PR TITLE
Add request method parameter for search and count

### PR DESCRIPTION
**Pull request by alamirault**
This PR allow to change request method for search and count as discussed in #1441.

### BC BREAK

I also moved default request method from `GET` to `POST` as suggested by @ruflin in [his comment](https://github.com/ruflin/Elastica/issues/1441#issuecomment-363285144).

### CODE REVIEW

**Comment by ruflin** [comment]
@alamirault Thanks for taking this on and sorry for the late reply, was on paternity leave ;-) I restarted CI to see if it was just a temporary failure or not. I assume your commit it based on current master?

**Comment by alamirault** [comment]
Congratulation ! Yes is based on current master.
Some tests failed because POST is set by default and they check dynamic changes. Should I delete them?

**Comment by ruflin** [comment]
Thanks :-) Should the tests be deleted or just adapted? Can you share a link to the culprits?

**Comment by alamirault** [comment]
https://github.com/ruflin/Elastica/blob/bbe10bc2d16bed6041d98add9d66c01294a7f92f/test/Elastica/Transport/GuzzleTest.php#L46

I think this test must be deleted. Or I should rework my PR in order to keep GET by default, change to POST only if search have data. And the `$method` arg (nullable by default) allow to override this behavior. I think is less predictive.

**Comment by ruflin** [comment]
If POST is the expected default, I think we should fully switch to POST and not have as you said, a less predictive behaviour. So far I can't see any downsides?

+1 on deleting the test.

**Comment by alamirault** [comment]
Code is rebased and I deleted the test.

**Pull request merged**
