### PR TITLE
Add WeightedAvg aggregation

### PR DESCRIPTION
**Pull request by romainneutron**
Replace #1770

### CODE REVIEW

**Comment by ruflin** [comment]
@romainneutron Can you check CI?

**Comment by romainneutron** [comment]
Hello,
It should be okay now.

**Comment by ruflin** [comment]
@romainneutron Thank you for the contribution! Feel free to open a backport PR to 6.x if you need it here too.

**Comment by romainneutron** [comment]
@ruflin Thanks! Done in #1773

**Pull request merged**
