### PR TITLE
Added setMinDocCount and setExtendedBounds options

### PR DESCRIPTION
**Pull request by markeilander**
Changed the correct file this time ;-)

### CODE REVIEW

**Comment by ruflin** [comment]
Merged, thx.

**Comment by CedCannes** [comment]
@markeilander thank you for your work , I just need to use " extended_bound " :+1: 
By cons it seems that the function setMinDocCount already existed in Histogram

https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Aggregation/Histogram.php#L55

There are two functions to do the same...

**Comment by ruflin** [comment]
@CedCannes Good point. I forgot about this one. @markeilander Can you remove the duplicate or use it as proxy? Because I like the "short" version naming.

**Comment by markeilander** [comment]
Made a new pull request: https://github.com/ruflin/Elastica/pull/950

**Pull request merged**
