### PR TITLE
missing childrenAggregation added

### PR DESCRIPTION
**Pull request by HKandulla**
@ruflin I started a new clean Pull Request because I think I messed up the git history with rebasing the release-2.3 branch on top of master. I closed: https://github.com/ruflin/Elastica/pull/1057

### CODE REVIEW

**Comment by ruflin** [comment]
@HKandulla LGTM. Waiting for travis to go green.

**Comment by HKandulla** [comment]
@ruflin finally:-) I must still do a `git rebase master`, right?

**Comment by ruflin** [comment]
In case you planned to do this PR for master, it is not needed.

**Comment by HKandulla** [comment]
I wanted to do the PR for master and release-2.3.

**Comment by ruflin** [comment]
One PR can only be for one branch at a time. So this looks good for the `master` branch. As all is green, ok for you if I merge this one?

**Comment by HKandulla** [comment]
yes, please. Thanks for all the help!

**Comment by ruflin** [comment]
Merged. Thanks for the contribution.

**Pull request merged**
