### PR TITLE
Use Null Coalesce Operator

### PR DESCRIPTION
**Pull request by carusogabriel**
Following #1420

### CODE REVIEW

**Comment by p365labs** [comment]
ok LGTM!

**Comment by ruflin** [comment]
@p365labs Minor comment: squash / merge or whatever it's called in the future to not have the merge commit in the history: https://github.com/ruflin/Elastica/commits/master

**Comment by p365labs** [comment]
@ruflin my first merge... my first mistake... it looks like it was already rebased... I will be more careful next time. sorry.

**Comment by ruflin** [comment]
@p365labs Nothing wrong happened here, it's only clicking a different button and personal preferences. Default on Github is with the merge commit. I normally use squash merge as I assume 1 PR = 1 commit in the end.

**Pull request merged**
