### PR TITLE
Missing ChildrenAggregation added

### PR DESCRIPTION
**Pull request by HKandulla**

### CODE REVIEW

**Comment by ruflin** [comment]
Travis did not run on this PR because of the following line :-( https://github.com/ruflin/Elastica/blob/master/.travis.yml#L8

Could you add a line with the release-2.3 branch to the PR?

**Comment by HKandulla** [comment]
@ruflin I tried to squash my commits with `git rebase -i HEAD~3.`, but I am not sure if that worked out ok. If not, could cou please advice me what to do. Thanks.

**Comment by ruflin** [comment]
You have to rebase on top of `release-2.3` branch, means your command would be `git rebase -i release-2.3`. I assume you have the most recent version of the release-2.3 branch checked out locally?

**Comment by ruflin** [comment]
Thanks for adding travis to the branch. The build looks good.

**Comment by HKandulla** [comment]
@ruflin Thanks for explaining. I will just do a clean new PR, ok?

**Comment by ruflin** [comment]
@HKandulla That also works for me if you feel more comfortable in doing that.

**Pull request closed without merging**
