### PR TITLE
Add Query String when put mapping (for example update_all_types)

### PR DESCRIPTION
**Pull request by daviddlv**
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#merging-conflicts

### CODE REVIEW

**Comment by ruflin** [comment]
@daviddlv Thanks for the addition. Could you add an integration test for this to make sure it works as expected? Please also update the CHANGELOG.md.

**Comment by lucascherifi** [comment]
Same problem for me, daviddlv could you please add a test ?

**Comment by ssalat** [comment]
What is the status of this PR?

**Comment by ruflin** [comment]
@ssalat It still requires some tests and Changelog entry. Interested to take this one over?

**Comment by p365labs** [comment]
@ruflin I'll take it if it's not a problem

**Comment by ruflin** [comment]
@p365labs That would be great.

**Comment by ssalat** [comment]
When will it be merged into the master branch?

**Comment by p365labs** [comment]
already merged :)
have a look [this PR](https://github.com/ruflin/Elastica/pull/1312)

**Comment by ssalat** [comment]
great, thanks! :)

**Comment by ruflin** [comment]
@p365labs This means we can close this one, right?

**Comment by p365labs** [comment]
yes @ruflin  we can close it :)

**Pull request closed without merging**
