### PR TITLE
use key and current without create new array

### PR DESCRIPTION
**Pull request by ReenExe**
Test it http://sandbox.onlinephpfunctions.com/code/289e92423ceab61f9b94793a9a1557c4574bef4b

### CODE REVIEW

**Comment by merk** [comment]
This change needs a unit or functional test, since there is no test coverage of CandidateGenerator with toArray()

**Comment by ReenExe** [comment]
```php

class Container
{
    private $array;

    public function __construct(array $array)
    {
        $this->array = $array;
    }

    public function getArray()
    {
        return $this->array;
    }
}

$container = new Container([
    'a' => 1,
    'b' => 2,
]);

foreach ($container->getArray() as $key => $value) {
    echo "$key => $value\n";
}

echo key($container->getArray()) === 'a' ? 'success' : 'fail';
echo "\n";
echo current($container->getArray()) === 1 ? 'success' : 'fail';
90
$container = new Container([
    1,
    2,
]);

foreach ($container->getArray() as $key => $value) {
    echo "$key => $value\n";
}

echo key($container->getArray()) === 0 ? 'success' : 'fail';
echo "\n";
echo current($container->getArray()) === 1 ? 'success' : 'fail';
```
`$generator` is copy of array that reseted - so we can use `key($generator)` and `current($generator)`

**Comment by ruflin** [comment]
@ReenExe It would be great if you could directly use this code to create a unit test out of it. Let me know if you have troubles setting up the test environment.

**Comment by ReenExe** [comment]
@ruflin, ok, find time to setup this week

**Comment by ruflin** [comment]
@ReenExe ok, ping me if something doesn't work as expected. In case you have docker and docker-compose installed, `make tests` should do the job.

**Comment by ruflin** [comment]
@ReenExe Did you have a chance to add some unit tests here?

**Comment by ReenExe** [comment]
@ruflin, Sorry, agree to close and re-open when possible

**Comment by ruflin** [comment]
@ReenExe We can also keep it open if you think you will get to it some day. Otherwise feel free to close it yourself.

**Comment by ReenExe** [comment]
Find `weakness` in the code and write tests are more easier to me - than install environment, but hope do it

**Comment by ruflin** [comment]
yeah, docker and windows :-) best is probably to try it inside a virtualbox. alternatively if you have phpunit and php locally, it should also work. If you test it just on your local PHP version and then travis tests all the other versions, that is fine for me.

**Comment by ReenExe** [comment]
@ruflin, You give good idea for cheat - i have `main` project (Ubuntu + Vagrant + Elastica) and in subdirectory import `Elastica` for tests - possible will be success.  Will try this week

**Pull request closed without merging**
