### PR TITLE
Allow for string interval in Histogram aggregations

### PR DESCRIPTION
**Pull request by dinamic**
I found this issue today and thought I could contribute a bug fix.

I can see its already fixed for newer releases, but 5.x still has it wrong. :)

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for the contribution.

**Comment by dinamic** [comment]
@ruflin I can see multiple unreleased changes in the 5.x tree. The last release - 5.3.5 was in January. Do you mind preparing a new one?

**Comment by ruflin** [comment]
@thePanz As our 5.x release master, WDYT? :-)

**Comment by thePanz** [comment]
@ruflin I'll backport it :)

**Comment by ruflin** [comment]
@thePanz You mean release it? This is already the backport :-)

**Comment by thePanz** [comment]
@ruflin sorry, it was a typo :)
PR for the release is here: https://github.com/ruflin/Elastica/pull/1658

**Pull request merged**
