### PR TITLE
Missing ChildrenAggregation added

### PR DESCRIPTION
**Pull request by HKandulla**

### CODE REVIEW

**Comment by ewgRa** [comment]
Thanks for PR.

Can you add tests please? You can check AvgTest as an example.

**Comment by HKandulla** [comment]
@ewgRa Thanks, I added a functional test, please let me know if there is something else missing.

**Comment by ruflin** [comment]
@HKandulla Unfortuntately your tests seems to fail: https://travis-ci.org/ruflin/Elastica/jobs/116853091#L2070

```
1) Elastica\Test\Aggregation\ChildrenTest::testChildrenAggregation
Elastica\Exception\ResponseException: can't add a _parent field that points to an already existing type
/elastica/lib/Elastica/Transport/Http.php:171
/elastica/lib/Elastica/Request.php:172
/elastica/lib/Elastica/Client.php:627
/elastica/lib/Elastica/Index.php:515
/elastica/lib/Elastica/Type.php:520
/elastica/lib/Elastica/Type/Mapping.php:273
/elastica/lib/Elastica/Type.php:301
/elastica/test/lib/Elastica/Test/Aggregation/ChildrenTest.php:33
/elastica/test/lib/Elastica/Test/Aggregation/ChildrenTest.php:86
```

**Comment by ruflin** [comment]
@HKandulla Please also update the CHANGELOG.md file.

**Comment by HKandulla** [comment]
@ruflin Thanks. The test didn't fail locally and I don't really understand the message "can't add a _parent field that points to an already existing type" but I will look into it and try to fix.

**Comment by HKandulla** [comment]
@ruflin my mistake, I meant to make a pull request in the release-2.3 branch which runs on Elasticsearch 1.7.* This restriction only exists since Elasticsearch 2.* Sorry

**Comment by HKandulla** [comment]
@ruflin I changed the order of the mapping, to have the child-mapping before the parent-mapping. This is only necessary for ES 2.* (https://discuss.elastic.co/t/adding-child-types-in-2-0/33267). 
I work with the 2.3-branch but I made a PR on the master branch too in case anyone else needs this feature.

**Comment by ruflin** [comment]
@HKandulla Thanks a lot for digging into this. We should definitively have it also in master. Could you rebase on top of master and squash the commits (in case you feel comfortable with that).

**Pull request closed without merging**
