### PR TITLE
Prepare 7.1.0 release

### PR DESCRIPTION
**Pull request by deguif**

### CODE REVIEW

**Review by ruflin — APPROVED** [review]
LGTM. Can you check if there are also any changes we need to make to the README.md file?

Here is my release checklist: https://elastica.io/release/how-to-create-an-elastica-release.html

I normally update also Elastica.io with the most recent docs, I can take care of that after the release.

**Comment by deguif** [comment]
@ruflin I think we could wait for the Elasticsearch official library to support PHP 8.0 before releasing 7.1.0. WDYT?

@ezimuel commented recently on https://github.com/elastic/elasticsearch-php/pull/1063 so I'm hoping support for PHP 8.0 there will be shipped soon.

**Comment by ruflin** [comment]
++ on waiting for the official client to support 8.0.

Lets make sure we rebase than again as the changelog will contain many more things :-D

**Comment by ruflin** [comment]
Let me know when this is ready and I should have another look. Lots has happened since this got opened :-D

**Comment by ruflin** [comment]
@deguif I see a few of the referenced PR's merged. Is this still blocked?

**Comment by jmsche** [comment]
elasticsearch-php 7.11.0 was released today with PHP 8 support, maybe this can unlock the release here?

**Comment by deguif** [comment]
Yes, let's release here ;)

**Comment by deguif** [comment]
@ruflin could you have a look to the changelog now that it's ready to publish.

**Review by ruflin — APPROVED** [review]
LGTM!

**Pull request merged**
