### PR TITLE
Add support for multiple bucket sort orders

### PR DESCRIPTION
**Pull request by cjost1988**
* Added `Aggregation\Terms::setOrders`
* Added test for `Aggregation\Terms::setOrders`
* Linter fixed another comment

If you want me to remove the linter fix, I'll can remove it. But I just followed the instructions and the linter changed the line. And since it was just one small change I took it into my PR.

### CODE REVIEW

**Comment by ruflin** [comment]
@cjost1988 Thank you for the high quality PR. Changelog, linting, tests - everything there ❤️

**Comment by cjost1988** [comment]
lol I just wanted to add the pull request link in the changelog :D

Thank you for your quick process. Glad to help improving.
And in the end we all benefit from good quality ;)

**Comment by ruflin** [comment]
haha, missed that one. Feel free to open an other PR, otherwise will fix it on release day when going through the changelog.

**Comment by cjost1988** [comment]
@ruflin https://github.com/ruflin/Elastica/pull/1481 is containing the fix for the changelog.

Thanks :)

**Pull request merged**
