### PR TITLE
Clear code

### PR DESCRIPTION
**Pull request by ReenExe**

### CODE REVIEW

**Comment by ReenExe** [comment]
Magic #1096 - have conflict - merge + reopen = conflict solved

**Comment by ruflin** [comment]
@ReenExe As mentioned earlier, these changes must be made in the linter to be automated: https://github.com/ruflin/Elastica/blob/master/.php_cs#L19 Otherwise every time I run `make lint` before a release, all your changes will be reverted.

**Comment by ruflin** [comment]
Also as discussed before, separate the PR's for the changes from array to [] and the reordering of commands.

**Comment by ReenExe** [comment]
@ruflin, in https://github.com/ruflin/Elastica/blob/master/.php_cs#L19 maybe need change for `short_array_syntax`?

**Comment by ruflin** [comment]
@ReenExe You have to check the phpcs docs what the available config options are. Probably [] is even default and this line could be removed? To test it just run `make lint` locally (can take some time).

**Comment by ReenExe** [comment]
@ruflin, Agree, but now far from `fast` machine - but soon `make lint`

**Comment by ReenExe** [comment]
@ruflin, How about i `explode` changes to `little` part - and after will adding by steps?

**Comment by ruflin** [comment]
@ReenExe 👍  That is exactly what I mean by splitting up the PR in small parts. So we can merge one by one.

**Comment by ReenExe** [comment]
move to #1121, other try with auto CS

**Pull request closed without merging**
