### PR TITLE
fix suggest API from PR #460

### PR DESCRIPTION
**Pull request by tiger-seo**

### CODE REVIEW

**Comment by ruflin** [comment]
@tiger-seo Thanks a lot for the contribution. Could you update the CHANGELOG with the change? Can you also share some details on what was broken? If we fix something, it is always good to have a small tests to confirm what was broken before and now is fixed. Could you also add a small test?

**Comment by tiger-seo** [comment]
@ruflin please, see https://github.com/ruflin/Elastica/pull/510#commitcomment-9103251

**Comment by ruflin** [comment]
@tiger-seo Ah, perfect 👍 Could you update the PR with the above suggestions?

**Comment by ruflin** [comment]
@tiger-seo Any updates here?

**Comment by ruflin** [comment]
@tiger-seo Any updates on this one?

**Comment by tiger-seo** [comment]
really sorry, but i can't complete this :(

**Comment by tiger-seo** [comment]
maybe it is better to close it

**Comment by ruflin** [comment]
@tiger-seo Lets keep it open and see if I or someone else can take it over.

**Comment by samdjstevens** [comment]
I could really do with this functionality getting merged in, what would I need to do to make it so?

**Comment by ruflin** [comment]
@samdjstevens Feel free to take over this PR. It would require an update to the CHANGELOG and a small test to confirm the changes.

**Comment by p365labs** [comment]
Hi @ruflin I know that ***_suggest*** end point has been deprecated but if you want I can make this PR ! what do u think ?

**Comment by ruflin** [comment]
@p365labs SGTM.

**Pull request closed without merging**
