### PR TITLE
Fix wrong method argument / signature

### PR DESCRIPTION
**Pull request by deguif**

### CODE REVIEW

**Comment by ruflin** [comment]
Something went wrong on CI but I restarted as it seemed like a download failure. How did you find this one?

**Comment by deguif** [comment]
@ruflin I used PHPStorm code inspections, it finds issues like this one.

**Comment by deguif** [comment]
CircleCI is seriously lagging since last days.

**Comment by ruflin** [comment]
CircleCI? We are using travis :-)

**Comment by deguif** [comment]
Yes sorry I meant `TravisCI` (Freudian slip: CircleCI is for work usage in my case).

**Review by ruflin — APPROVED** [review]

**Pull request merged**
