### PR TITLE
Add PHP 8.4 support

### PR DESCRIPTION
**Pull request by sidz**
This PR adds PHP 8.4 support

### CODE REVIEW

**Comment by ruflin** [comment]
Perfect as usual. Thanks!

**Comment by HypeMC** [comment]
@ruflin Hello, I'm just wondering, do you have an idea when this might get released, tnx.

**Comment by ruflin** [comment]
@HypeMC Let me see that I can get a release out in the next days but there are a few other competing things on my list. @thePanz Maybe you get to it?

**Comment by thePanz** [comment]
I can have a look @ruflin :)

**Comment by ruflin** [comment]
Thanks ;-) https://github.com/ruflin/Elastica/pull/2235

**Comment by HypeMC** [comment]
@ruflin @thePanz Thanks guys :smile:

**Pull request merged**
