### PR TITLE
Fixing bug in usage of ltrim

### PR DESCRIPTION
**Pull request by viable-hartman**
Pretty sure the intention of this was to remove the '/', not lose the path, which this would do. So fixing it. Looks like this has been in the code going back quite a while, so might want to port it back.

### CODE REVIEW

**Comment by ruflin** [comment]
This indeed looks odd :-( I wonder why this didn't break other things.

@viable-hartman 

* Could you add a changelog entry?
* Do you see a way we could test this change?

**Comment by ruflin** [comment]
@viable-hartman Thank you! Hoping you get some spare time soon ;-)

**Comment by deguif** [comment]
@viable-hartman would you be able to add a changelog?

**Comment by deguif** [comment]
@ruflin I just added a changelog here.
If you could a look as I planned it for `7.1.1` too ;)

**Review by ruflin — APPROVED** [review]

**Pull request merged**
