### PR TITLE
Change log standard

### PR DESCRIPTION
**Pull request by ruflin**
Introduction a new change log standard based on keepachangelog.com

### CODE REVIEW

**Comment by ruflin** [comment]
@im-denisenko @webdevsHub Please merge if this goes in the right direction.

**Comment by webdevsHub** [comment]
I would move the description to `CONTRIBUTING.md` and use "Unreleased" as h1

**Comment by im-denisenko** [comment]
Seems like issue referencing don't works in markdown, and all links must be explicitly specified. I add this change.

**Comment by ruflin** [comment]
@webdevsHub I suggest we introduce the CONTRIBUTING.md in a second pull request. I would like to add there some more details / rules for contributors.

**Comment by im-denisenko** [comment]
Merged.

**Pull request merged**
