### PR TITLE
Remote Filter\Terms for Elasticsearch 5.x

### PR DESCRIPTION
**Pull request by ChristopheBoucaut**
Remove the Filter\Terms class for next major release for Elasticsearch 5.x.

_Previous PR :_
The `execution` option of the terms filter is deprecated since [Elasticsearch 2.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_literal_terms_literal_query_and_filter).

Note : The Elastica\Filter\Terms class is deprecated so I don't know if my change is relevant.

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. I'm thinking if we should directly remove it as the next major release planned of Elastica is for 5.0

**Comment by ChristopheBoucaut** [comment]
Ok. So can we close this pull request and just wait the next major release to remove this class ?

**Comment by ruflin** [comment]
As the next major release will be based on master, it probably makes sense to directly change this PR and remove it here.

**Comment by ChristopheBoucaut** [comment]
Ok, I try to change the PR to remove the class (+test) this week-end.

**Comment by ChristopheBoucaut** [comment]
I updated the code to remove Filter\Terms class and I update tests. I was not able to run the tests :/

```
Waiting on elasticsearch(elasticsearch:9200) to start...............................
Elasticsearch is not running or is not healthy.
Address: elasticsearch:9200

Makefile:20 : la recette pour la cible « run » a échouée
make: *** [run] Erreur 1
```

**Comment by ChristopheBoucaut** [comment]
For the fail, i don't know :/ If I remove class, I need to remove 'filter' in the $filters array for all versions classes.

```
There was 1 failure:
1) Elastica\Test\QueryBuilder\VersionTest::testVersions
filter "terms" in Elastica\QueryBuilder\Version\Version090 must be defined in Elastica\QueryBuilder\DSL\Filter
Failed asserting that false is true.
/elastica/test/lib/Elastica/Test/QueryBuilder/VersionTest.php:51
/elastica/test/lib/Elastica/Test/QueryBuilder/VersionTest.php:34
```

**Comment by ruflin** [comment]
@ChristopheBoucaut Interesting error, was not thinking of this before. But this means we should remove all the older query builders completely as they will not work anymore (not only because of this change).

**Comment by ChristopheBoucaut** [comment]
@ruflin, I create a new PR to remove the older query builders and I will rebase this branch after or I remove query builder in this PR ?

**Comment by ruflin** [comment]
SGTM

**Comment by ruflin** [comment]
@ChristopheBoucaut Closing this PR as in the meantime all filters were removed so I don't think this is still needed. Please reopen if you see it differently.

**Pull request closed without merging**
