### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by im-denisenko** [comment]
I would suggest :
* Add `phpdoc_order` fixer to config file.
* Manually remove `@category` and close #299. `@package` already removed thanks to `phpdoc_no_package` fixer.
* Pin exact commit hash of php-cs-fixer in `require-dev` so this tool will always generate the same result as before (of course, while someone will not change pinned version)

**Comment by ruflin** [comment]
Sounds good to. Are you able to "push" into my pull requests?

**Comment by im-denisenko** [comment]
Yep, I can. I'll add these changes at evening.

**Comment by im-denisenko** [comment]
Done.

**Comment by ruflin** [comment]
Merged.

**Pull request merged**
