### PR TITLE
Fix typo in changelog

### PR DESCRIPTION
**Pull request by stchr**
just to avoid confusions...

### CODE REVIEW

**Review by ruflin — COMMENTED** [review]
Change LGTM. Somehow CI complains?

**Comment by stchr** [comment]
Hmm, same complaints as #2119? Probably a general issue with the tests...

**Comment by ruflin** [comment]
Seems like an update in some geo libs?

```
1) Elastica\Test\Aggregation\GeoBoundsTest::testGeoBoundsAggregation
Failed asserting that 37.782438984140754 matches expected 37.782438984141.
```

**Comment by ruflin** [comment]
Looking at the test directly: https://github.com/ruflin/Elastica/blob/master/tests/Aggregation/GeoBoundsTest.php#L42 I think we compare too many digits and should take a substring instead to only compare the digits that are actually set.

**Comment by ruflin** [comment]
I opened https://github.com/ruflin/Elastica/pull/2121 to potentially fix the test.

**Comment by ruflin** [comment]
https://github.com/ruflin/Elastica/pull/2121 just got merged, can you rebase on top of master?

**Review by ruflin — APPROVED** [review]

**Comment by ruflin** [comment]
No need for a rebase, merge commit is as good. I squash anyways on merge.

Thanks for the fix and sorry it took a bit longer to get it in.

**Pull request merged**
