### PR TITLE
Update Changelog for 5.x branch

### PR DESCRIPTION
**Pull request by thePanz**
A new release for 5.x should be tagged after merging this :)

### CODE REVIEW

**Comment by ruflin** [comment]
@thePanz Interested to become a Admin for the Elastica repo so you could also push such tags directly?

**Comment by ruflin** [comment]
@thePanz Happy to push the tag. But we should also have 1 more PR that cleans up the Changelog and introduces the release in the Changelog. Could you open one?

**Comment by thePanz** [comment]
@ruflin I'm glad for your offer! :) Please add me ad an admin (I'll work mainly on the 5.x branch, for now) :)

**Comment by ruflin** [comment]
@thePanz I added you to the list. Please ping me if you have any questions and thanks for all the help.

For releases, please make sure that the CHANGELOG is in line ;-) I often to a release PR first and then just create a tag from the branch (or use Github release feature).

**Pull request merged**
