### PR TITLE
fix empty string is not anonymous filter

### PR DESCRIPTION
**Pull request by ewgRa**
Add tests for Filters keys and fix for this test.

'' - is not anonymous key. Proof - 
empty-key

From discussion here https://github.com/ruflin/Elastica/pull/916#discussion-diff-37099377 and here https://github.com/ruflin/Elastica/pull/916#discussion_r39566782

### CODE REVIEW

**Comment by ewgRa** [comment]
Constructor default value changed. Kind of broke BC, but this is bugfix, and I think can"t be considered as broke BC.

**Comment by ruflin** [comment]
@ewgRa Looks good. Can you update the CHANGELOG.md?

**Comment by ewgRa** [comment]
done

**Comment by ruflin** [comment]
Merged, thx.

**Pull request merged**
