### PR TITLE
Added support for pools using DSN

### PR DESCRIPTION
**Pull request by Nyholm**
I was about to update https://github.com/Happyr/elastica-dsn which basically adds DSN support to 6.x. But then I saw that 7.x will have support for DNS but not for multiple hosts. 

Im sorry that I introduce a new dependency like this for such a small feature. I do need this feature in my app and I really wanted to try out nyholm/dsn:2.0 before I tag a stable release.

This will support any crazy DSN you may think of. See the full specification here: https://github.com/nyholm/dsn

Let me know what you think.

---

The PR is in draft as it should not be merged before nyholm/dsn:2.0 is released.

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for the addition. I'm always a bit on the fence about adding more external dependency at the same time, get rid of code to maintain is great. My initial reaction was that this might remove quite a bit of code on our end up it seems it is not the case. What else does the DSN lib to add as features to Elastica besides multi hosts or are we just missing multi hosts?

Do you know when 2.0 is planned to be shipped?

**Comment by Nyholm** [comment]
> What else does the DSN lib to add as features to Elastica besides multi hosts or are we just missing multi hosts?

Not much. The usual. =)
- Safer parsing with some error messages
- The ability to do DSN functions like `roundRobin(http://host1 http://host2)`

> My initial reaction was that this might remove quite a bit of code on our end up it seems it is not the case.

True. I wanted to keep BC. Ideally I would remove the `connections` key and force people to use a DSN function. That would also make it possible to validate the options to make sure the user dont misspell stuff.

> Do you know when 2.0 is planned to be shipped?

I plan to release it as soon we are happy here.

**Review by ruflin — COMMENTED** [review]
Haha, I missed the most important bit that you are the owner of the lib 🤦‍♂️ That simplifies things of course as you are in control of it and the release.

I'm good with moving forward here. This PR would also need a changelog entry.

**Comment by Nyholm** [comment]
I've released 2.0, PR is ready for review.

**Review by thomaspicquet — APPROVED** [review]

**Comment by ruflin** [comment]
@Nyholm Just wanted to merge this but unfortunately there is now a conflict with master :-( Could you rebased / merge in master? Sorry for the delay on my end which probably caused this.

**Comment by Nyholm** [comment]
No worries. 

PR is rebased. Tests should pass.

**Comment by ruflin** [comment]
@Nyholm Thanks for the contribution!

**Comment by Nyholm** [comment]
Wohoo. Thank you for merging

**Pull request merged**
