### PR TITLE
Add Stats Bucket for use

### PR DESCRIPTION
**Pull request by gbourgeat**
=> https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-stats-bucket-aggregation.html

### CODE REVIEW

**Comment by ruflin** [comment]
Awesome. Could you add a line to the changelog.md file?

**Comment by gbourgeat** [comment]
Yes I did it but Travis don't like that :/

**Comment by p365labs** [comment]
I've restarted the build... it looks like it failed the tests for CrossIndex which is deprecated. It smells as flaky test. I will have a look into it this week end.

**Comment by gbourgeat** [comment]
Thks

**Pull request merged**
