### PR TITLE
Enable Travis on 5.x branch

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by XWB** [comment]
@ruflin Looks like Travis cannot run due to the following error:

> The command "sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce=17.03.1~ce-0~ubuntu-trusty" failed and exited with 100 during .

Any clue?

**Comment by ruflin** [comment]
I remember we fixed something in the past in travis probably related to the distro we use. Check the master travis file for the diff to find what we changed.

**Comment by XWB** [comment]
@ruflin All green.

**Comment by ruflin** [comment]
@XWB Thanks for going through all the hoops to get this in.

**Comment by ruflin** [comment]
@XWB Thanks for your work on the 5.x branch. Finally 5.3.1 is out.

**Pull request merged**
