### PR TITLE
Fix Index->deleteByQuery array lazy loading

### PR DESCRIPTION
**Pull request by raphaelMalie**
This method was broken since the array lazy loading push.

### CODE REVIEW

**Comment by ruflin** [comment]
@raphaelMalie Thanks for the fix. Can you please update the CHANGELOG.md? Can you add a small tests that would fail before and is not successful to make sure we don't break it again?

**Comment by xjewer** [comment]
same bug in this line https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Type.php#L490

**Comment by ruflin** [comment]
@raphaelMalie Any updates here?

**Comment by xjewer** [comment]
>This method was broken since the array lazy loading push.

**Comment by raphaelMalie** [comment]
Hello, sorry I never wrote tests before and I have no time to learn it now :/ You can close this PR and apply the fix by yourself, it would be better if possible. Regards, Raphaël.

**Comment by xjewer** [comment]
>This method was broken since the array lazy loading push.

it can happen, if create Query from array

```php
Query::create(
    [
        'query' => [
            'ids' => [
                'values' => [1],
            ],
        ],
    ]
);
```

so, array set through `$this->setRawQuery($query);` and when execute `$Query->getQuery()` we get array instead Query object

**Comment by ruflin** [comment]
@raphaelMalie Thanks for the heads up. Will try to take your commit and add tests (or someone else who has the time :-) ).

@xjewer We should add a test and fix for that (if possible).

**Comment by ruflin** [comment]
This was now fixed in https://github.com/ruflin/Elastica/pull/1049

**Pull request closed without merging**
