### PR TITLE
Update to elasticsearch-php and drop php70 support

### PR DESCRIPTION
**Pull request by p365labs**
This PR remove dev-master dependencies for elasticsearch-php and as it drop support to PHP 7.0 I removed PHP 7.0 Docker and config files referencing to that version.

### CODE REVIEW

**Comment by p365labs** [comment]
as u can see there are a couple of error which I will fix during the weekend

**Comment by ruflin** [comment]
Can you elaborate on the PHP 7.0 support?

**Comment by p365labs** [comment]
composer.json has this requirement for 7.0 --> **PHP 7.1**

``` ],
  "require": {
    "php": "^7.1", 
    "ext-json": ">=1.3.7",
    "guzzlehttp/ringphp": "~1.0",
    "psr/log": "~1.0"
```

**Comment by ruflin** [comment]
Got it, make sense. Missed that "detail" ;-) I think we should update 2 changelog entries here:

* 1 for the change of the required php version
* 1 for updating the php elasticsearch dependency to a new major

**Comment by p365labs** [comment]
@ruflin fixed some tests, fixed elasticsearch-php version (^7.0) and addes some info related to the drop of php 7.0

**Comment by mejarrett** [comment]
Is there any ETA for merging these changes?

**Comment by p365labs** [comment]
@mejarrett merged.

**Pull request merged**
