### PR TITLE
Expose the number of shards from the Index settings

### PR DESCRIPTION
**Pull request by thePanz**
Expose the number of Shards from the index settings

### CODE REVIEW

**Comment by thePanz** [comment]
@ruflin The failures are related to an update on Travis, where the environment is not able to start, the code is not even tested :(
Are you aware of such failure?

**Comment by p365labs** [comment]
Hi all! Travis has updated their images .... now we have Ubuntu Trusty 14.04.... (not really fresh.. but it's ok). I'm testing a PR to allow new PR's to pass the tests and then, with more time, I will try to update .travis.yml in order to work properly with the new Trusty images. @ruflin

**Comment by p365labs** [comment]
@thePanz @ruflin I'm testing PR #1332. This will allow to patch the error on travis build

**Comment by ruflin** [comment]
@thePanz I merged the above PR from @p365labs Could you rebase on top?

**Comment by thePanz** [comment]
Thanks @p365labs ! :)
@ruflin rebased and pushed.. tests are starting :)

**Comment by thePanz** [comment]
@ruflin tests passed! yay! :)

**Comment by ruflin** [comment]
@thePanz Merged. Thanks for the ping.

**Pull request merged**
