### PR TITLE
fix #1423: remove deprecated each usage

### LINKED ISSUE #1423: \Elastica\Transport\Http uses deprecated each() function
`\Elastica\Transport\Http` code uses `each()` function which is deprecated as of PHP 7.2. This results in flooding logs with `E_DEPRECATED` entries. 

https://github.com/ruflin/Elastica/blob/23f2bf0c7cfdc15a219ada33bb17a4367b5ffddb/lib/Elastica/Transport/Http.php#L118

### PR DESCRIPTION
**Pull request by mkosiedowski**

### CODE REVIEW

**Comment by ruflin** [comment]
@mkosiedowski Thanks for the fix. Could you add an entry to the CHANGELOG.md file?

**Comment by mkosiedowski** [comment]
Sure @ruflin, just did it :)

**Comment by ruflin** [comment]
@mkosiedowski Merged, thanks.

**Comment by stof** [comment]
@ruflin any plan to talk a release supporting PHP 7.2 without deprecation ?

**Comment by ruflin** [comment]
@stof You mean something like 6.0.1 or 6.1? Yes, I just didn't get to it yet. Sorry about that :-(

**Comment by stof** [comment]
yeah, sorry. I meant `tag`, not `talk` in my previous comment.

**Comment by stof** [comment]
@ruflin is Elastica 6 compatible with ElasticSearch 5 or no ? And if no, is there any plan to backport the PHP 7.2 compatibility to a 5.x release too ? I have not yet migrated to ElasticSearch 6 (it requires me to stop relying on types first), but I still would like to migrate to PHP 7.2 before that.

**Comment by ruflin** [comment]
@stof Elastica is not compatible with ES 5 (or at least not tested). There are quite a few things currently backported to 5.x, also the 7.2 part is already done: https://github.com/ruflin/Elastica/pull/1428

**Pull request merged**
