### PR TITLE
added filter path option

### PR DESCRIPTION
**Pull request by mhernik**

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Could you update the CHANGELOG.md with this change? And any chance you could add an integration tests that covers the filter_path? Check out the file `SearchTest.php` for some examples.

**Comment by mhernik** [comment]
Sure! Will do so and I let you know.

**Comment by mhernik** [comment]
Changelog and test added.

**Comment by ruflin** [comment]
@mhernik merged. Thanks a lot for the contribution.

**Comment by insekticid** [comment]
same option is missing in MultiSearch https://github.com/ruflin/Elastica/blob/master/src/Multi/Search.php

**Pull request merged**
