### PR TITLE
Add missing @throws annotation to Client::request and related methods

### PR DESCRIPTION
**Pull request by VincentLanglet**
Backport of https://github.com/ruflin/Elastica/pull/2152

### CODE REVIEW

**Comment by ruflin** [comment]
Thx!

**Comment by VincentLanglet** [comment]
You're welcome @ruflin ; do you mind creating a release with this change ? 

Thanks

**Comment by VincentLanglet** [comment]
You're welcome @ruflin, do you mind doing a release ?

**Comment by ruflin** [comment]
Yep, will try to get to it soonish. If @deguif or @thePanz beats me, I'll not complain.

I assume you mean a release from the 7.x branch, right?

**Comment by VincentLanglet** [comment]
> I assume you mean a release from the 7.x branch, right?

Yes, thanks

**Comment by ruflin** [comment]
@VincentLanglet Sorry for the delay, 7.3.1 is out: https://github.com/ruflin/Elastica/releases/tag/7.3.1

**Pull request merged**
