### PR TITLE
Fix #1559 - Backported from #1561

### LINKED ISSUE #1559: Not compatible with the php 5.3.3 version
https://github.com/ruflin/Elastica/blob/51faf4fd6c3e80c121dc30776d8f3f6e56ea7a8f/lib/Elastica/Query.php#L404

This is not compatible with the php 5.3.3 version

if (isset($this->_params['post_filter']) && 0 === count(($this->_params['post_filter'])->toArray())) {
            unset($this->_params['post_filter']);
}

request.CRITICAL: Symfony\Component\Debug\Exception\FatalErrorException: Parse Error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) (uncaught exception)

### PR DESCRIPTION
**Pull request by jmsche**
Fixes #1559, replaces #1561

### CODE REVIEW

**Comment by jmsche** [comment]
Sorry I missed your request for an updated CHANGELOG (flu & angina do not help).

That's fixed!

**Comment by romaricdrigon** [comment]
I confirm the fix works on PHP 5.6, could it be merged please @ruflin ?

**Comment by jmsche** [comment]
Could you please create a release for this patch? Thanks.

**Comment by ruflin** [comment]
I just created tag `2.3.3`.

**Comment by jmsche** [comment]
Thank you :)

**Comment by ruflin** [comment]
Can you please test it and report back if things work as expected? @romaricdrigon Would be great to get your feedback too.

**Comment by jmsche** [comment]
@ruflin Seems the release was not published to packagist somehow, could you force it? Thanks :)

**Comment by ruflin** [comment]
What you mean by packaging? composer?

**Comment by jmsche** [comment]
Packagist or composer yes, see https://packagist.org/packages/ruflin/elastica where the 2.3.3 version has not been published here

**Comment by romaricdrigon** [comment]
The tag is no published yet on Packagist (https://packagist.org/packages/ruflin/elastica), I couldn't update to test it yet. I believe you should have a "force update" in your Packagist backend, if you are registered as maintainer over there.

**Comment by ruflin** [comment]
I logged in and hit update. Let's see if that helped.

**Comment by romaricdrigon** [comment]
Great, I could update to 2.3.3. Everything is working correctly on PHP5.6.

**Comment by Tobion** [comment]
hey, what's the reason this was merged into branch https://github.com/ruflin/Elastica/tree/2.x-temp but not https://github.com/ruflin/Elastica/tree/2.x ? Can we merge the branches and delete the "temp" one?

**Comment by Tobion** [comment]
Or just delete both 2.x branches because they are not maintained anymore?

**Comment by ruflin** [comment]
I think both are still needed:

* 2.x-temp: To do future 2.x releases. Even though they are EOL, normally if a user goes through the hassle to fix a but there, I still do a release or at least we get into the branch
* 2.x: Contains a change I do not want to release in 2.x but I know some users depend on it.

So the naming is super confusing and 1 commit should have never been merged into 2.x and 2.x should be what 2.x-temp is today 🤦‍♂ 

Hopefully 2.3.2 is a bit behind 2.x-temp 🤞 

Did you clean up some Elastica branches? Good to know :-D

**Pull request merged**
