### PR TITLE
Add sum_bucket & avg_bucket aggregations

### PR DESCRIPTION
**Pull request by josselinh**
Hello @ruflin 

I need sum_bucket & avg_bucket, so I added them.

Hope it's ok

https://github.com/ruflin/Elastica/issues/1279

### CODE REVIEW

**Comment by josselinh** [comment]
Just FYI, I have ElasticSearch 5.6

**Comment by XWB** [comment]
Perfect timing as we need `sum_bucket` as well.

@ruflin Please consider this PR before releasing 5.3.1 :)

**Comment by ruflin** [comment]
@josselinh Can you add some tests to this and a CHANGELOG?

Also it would be great to also have this in master. I suggest to have first a PR against master and then cherry pick it to 5.x.

**Comment by josselinh** [comment]
Hello @ruflin,
I modified the changelog and added the tests as you wanted.
I'll make you a new PR for the branch master later.

**Comment by ruflin** [comment]
@josselinh Thanks a lot for the contribution and also the tests. Can you directly open the PR against master to make sure we don't forget about it and have all the features from 5.x also in master?

**Pull request merged**
