### PR TITLE
Support setRefresh as wait_for, true, false or empty

### PR DESCRIPTION
**Pull request by qqqqb**

### CODE REVIEW

**Comment by qqqqb** [comment]
Ref #1475

**Comment by ruflin** [comment]
Could you add some tests to this PR and entry to the CHANGELOG?

So far it seems this change breaks the existing tests.

**Comment by qqqqb** [comment]
I'm not sure why this failed, What I did is allow to accept the following
'true' by (string) '', (integer) 1, (Boolean) True
'wait_for' by (string) 'wait_for'
'false' (integer) 0, (Boolean) False

And what I wrote is
`if (is_string($refresh) && strlen($refresh) == 0) {
          $refresh = True;
        }
        if ($refresh != 'wait_for') {
          $refresh = $refresh ? 'true' : 'false';
        }`

**Comment by ruflin** [comment]
I haven't checked in detail yet. It could also be that we found an error in the test case that fails. 

In any case it would be helpful to add tests for this that will also make it easier to tell if the implementation is correct.

**Comment by safwenbs** [comment]
Hello, it would be nice to merge this in order to handle the wait_for option as mentionned in the elastic doc

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

`refresh
(Optional, enum) If true, Elasticsearch refreshes the affected shards to make this operation visible to search, if wait_for then wait for a refresh to make this operation visible to search, if false do nothing with refreshes. Valid values: true, false, wait_for. Default: false.`

**Comment by ruflin** [comment]
@safwenbs Interested to take the PR over?

**Comment by deguif** [comment]
Closing as https://github.com/ruflin/Elastica/pull/1791 got merged.

**Pull request closed without merging**
