### PR TITLE
Added var_export because sometime $error is an array

### PR DESCRIPTION
**Pull request by leopoiroux**

### CODE REVIEW

**Comment by ruflin** [comment]
Which version of Elastica are you using? getErrorMessage should return always a string. See https://github.com/ruflin/Elastica/blob/f545465dd4d5acd020ebf1c1e7846fbefcc0f399/lib/Elastica/Response.php#L130

**Comment by leopoiroux** [comment]
Hi, I use the last version (2.3.2)
Thks for your help

**Comment by ruflin** [comment]
Version 2.3.2 of Elastica is not compatible with elasticsearch 2.x. Please update the version 3.x of Elastica.

**Comment by ruflin** [comment]
Closing this issue as I think it is related to using incompatible version of Elastica and elasticsearch. Please reopen if that is not the case.

**Pull request closed without merging**
