### PR TITLE
Add inferred return types

### PR DESCRIPTION
**Pull request by thePanz**
Applied those by using Rector
See: https://getrector.org/blog/how-to-automatically-add-return-type-declarations-without-breaking-your-code

### CODE REVIEW

**Comment by deguif** [comment]
That should target the next major release as that would break backward compatibility. WDYT?

**Comment by thePanz** [comment]
> That should target the next major release as that would break backward compatibility. WDYT?

The return types were inferred by the actual code's usage and return values.
But I see the point, it could break 3rd party codes if they extend and overwrite one of the changed methods.
Is that what you mean?

**Comment by deguif** [comment]
> But I see the point: it could break 3rd party codes if they extend and overwrite one of the changed methods.

Yes absolutely

**Comment by thePanz** [comment]
right, I'll close this PR.
Let's hope to include Rector when we'll move to the v8.x version in the future

**Comment by thePanz** [comment]
@deguif on a second thought, wouldn't this PR introduce the same BC-break as #2085?

**Pull request closed without merging**
