### PR TITLE
Make MatchQuery.php in 6.x valid PHP

### PR DESCRIPTION
**Pull request by reedy**
Follows up https://github.com/ruflin/Elastica/pull/1898

### CODE REVIEW

**Comment by reedy** [comment]
Sorry about this!

**Review by deguif — APPROVED** [review]

**Comment by ruflin** [comment]
@deguif As CI is not run, I assume this branch is missing in our Github actions?

**Comment by reedy** [comment]
> @deguif As CI is not run, I assume this branch is missing in our Github actions?

AFAIK Github Actions will only run where there's the .github/foo.yml file in the tree, so yeah, there's none in 6.x, so doesn't run

**Comment by deguif** [comment]
Let's fix it for the moment. Will try to add some check on `6.x` later.

**Pull request merged**
