### PR TITLE
Send bulk requests using POST instead of PUT

### PR DESCRIPTION
**Pull request by hakman**
Fixes issue #1010.

### CODE REVIEW

**Comment by ewgRa** [comment]
I wondering, is this the backward compatibility broke or not?

Theoretically this change can broke something, because you have real case why this change needed and change must be added to changelog as BC broke.

What do you think?

**Comment by hakman** [comment]
ES treats both PUT and POST bulk the same way, so I don't see any backwards compatibility issue. This would just make the Elastica behave like most other ES libs.
https://github.com/elastic/elasticsearch/blob/2.1/rest-api-spec/src/main/resources/rest-api-spec/api/bulk.json

**Comment by ruflin** [comment]
@hakman LGTM. Can you update the CHANGELOG.md?

**Comment by hakman** [comment]
Done, thank you!

**Comment by ruflin** [comment]
@hakman Thanks for the contribution.

**Pull request merged**
