### PR TITLE
Add a PHPUnit deprecations handler

### PR DESCRIPTION
**Pull request by deguif**
This will now allow to list all deprecations notices during PHPUnit execution.
Screenshot 2020-11-10 at 15 01 17

### CODE REVIEW

**Comment by ruflin** [comment]
Oh, sooo many deprecation notices ... Nice addition.

**Comment by ruflin** [comment]
It seems the deprecation list fails the build. Is this intentional and you plan to clean it up or should we make this a test that must not pass yet?

**Comment by deguif** [comment]
Yes, I'm fixing the tests and just allow the right deprecations.

**Comment by deguif** [comment]
@ruflin PR is now ready and green.

**Review by ruflin — APPROVED** [review]

**Pull request merged**
