### PR TITLE
Add authors in changelog

### PR DESCRIPTION
**Pull request by deguif**
This way, when publishing a new release, a contributors section should be automatically added by github.

### CODE REVIEW

**Review by ruflin — APPROVED** [review]
Nice, didn't know this exists.

**Comment by thePanz** [comment]
Can you rebase this on "master"?
 merged #2045 and this branch has now conflicts

**Comment by deguif** [comment]
Here's the result
Screenshot 2021-12-09 at 10 17 30

**Comment by thePanz** [comment]
Cool! Thank you for updating the release notes too! :+1: 
ps: the "New Contributors" section was automatically generated by GitHub shortcut .. should we keep it? WDYT?

**Comment by ruflin** [comment]
I like the "New Contributors" part and would keep it.

**Pull request merged**
