### PR TITLE
Allow PHP 7.0 failures

### PR DESCRIPTION
**Pull request by XWB**
* We should aim at 100% PHP 7 compatibility
* PHP 5.3 works anyway

### CODE REVIEW

**Comment by XWB** [comment]
Travis passes, not sure why `codecov/project` fails.

**Comment by ruflin** [comment]
@XWB Codecov fails because it is below 60%. They have a bug in the PHP coverage reporting, so it is not consistent. 

The reason I would like to keep PHP 5.3 in allow failures is to make it obvious, that yes it still works but we could get rid of it at any time. There are already some hacks for PHP 5.3 that we need to cleanup earlier or later.

**Comment by XWB** [comment]
@ruflin :+1: I restored the PHP 5.3 entry.

**Comment by ruflin** [comment]
The title is a little bit wrong as it is more about "Not allow" PHP 7 failures ;-)

**Comment by ruflin** [comment]
Merged anyways :-)

**Pull request merged**
