### PR TITLE
Cleanup gitignore file

### PR DESCRIPTION
**Pull request by thePanz**
A .gitignore in a project should only cover artifacts caused by the contained source code, not those caused by the person

### CODE REVIEW

**Comment by ruflin** [comment]
In theory I agree on the above, in practice I don't. It's not a burden I want to put on our contributors and even less on myself to check every PR for `.DS_Store` files or other files that were added accidentally and then ask the contributor to update his PR again. I rather have control on the repository end what must be ignored and what not.

**Comment by ruflin** [comment]
@thePanz Would you be ok with closing this PR?

**Comment by thePanz** [comment]
@ruflin do you mean "closing" or "merging"? :)

We got 2 approvals (plus mine)... maybe @Nyholm wants ti share their point of view (to convince you?) :wink:

**Comment by Nyholm** [comment]
I understand that some repositories attract contributors that are more likely to accidentally add their `.DS_Store`. I have no idea if this is such repository or not. I find it rather rare to see a PR that has included `.DS_Store` or similar metafiles. 

I approved this PR because it is good practise to leave OS and IDE metafiles to the global gitignore. 

I would also recommend that IF there is a problem with adding `.DS_Store` to a PR, it could be solved with a CI test.

**Comment by ruflin** [comment]
@thePanz I'm more thinking about not merging it. As said before, I agree with the theory but I don't see the benefits for the project and contributors. Is there any downside of having these files in .gitignore?

**Comment by deguif** [comment]
Can I close this one?

**Comment by ruflin** [comment]
I'm going to close this one as I was the one that objected. Hope it is ok for @thePanz and @Tobion .

**Pull request closed without merging**
