### PR TITLE
DockerPHP AllowSymfonyFlexPlugin on phpuser for phpunit

### PR DESCRIPTION
**Pull request by daminux**
Allow (to false) SymfonyFlex plugin for phpuser on make docker-run-phpunit

Love tests on docker ;)

### CODE REVIEW

**Comment by ruflin** [comment]
Can you share a bit more background (link or comment) on what this exactly does / allows?

**Comment by daminux** [comment]
> Can you share a bit more background (link or comment) on what this exactly does / allows?

As noted, I really like the idea of docker fulfilling its role of abstracting the host's technical stack.

After recovering the projects to work on the unit testing part, I executed make docker-start, then make docker-run-phpunit and I encountered this error, for which I propose this fix (see screenshot below).

image

**Comment by ruflin** [comment]
My initial reaction was, it seems like this is the wrong place but I just found out, 4 years ago we added this dependency to the project :-) https://github.com/ruflin/Elastica/blob/8bcb02d428fa4e5c472175166bc56a5a39b5c97b/Makefile#L19

**Review by ruflin — COMMENTED** [review]
Change LGTM. Can you add a quick note to the changelog?

**Comment by daminux** [comment]
Done !
sorry mistake bad group of changes

**Comment by daminux** [comment]
move type of changes ok.

**Comment by ruflin** [comment]
@daminuxfork Thank you for the contribution!

**Pull request merged**
