### PR TITLE
Use correct Put class for updating settings. Fixes #1295

### LINKED ISSUE #1295: [5.2] Index::setSettings broken?
It seems that in 5.2+ `setSettings` on an `Index` is broken. It tries to set the settings on the whole cluster instead of only the index.

In 5.1 this still works.

If I take a short look at the code it seems `Elasticsearch\Endpoints\Cluster\Settings\Put` is the wrong class and we should use `Elasticsearch\Endpoints\Indices\Settings\Put` instead?

### PR DESCRIPTION
**Pull request by nickygerritsen**
This fixes #1295 and adds a test that verifies this.

### CODE REVIEW

**Comment by ewgRa** [comment]
Strange, that another tests in this SettingsTest class are written in a same way, but they do not fail...

I haven't ability to check it right now, but did your test fail, if you revert changes in "lib/Elastica/Index.php" back?

Maybe there is wrong tests if it is not fail...

**Comment by nickygerritsen** [comment]
Yeah my test failed before. The other tests in this class are different: they use `getSetting` and then `set` on that object instead of directly using `setSettings` on the index. The later is what was broken (and not tested at all yet).

**Comment by ewgRa** [comment]
@nickygerritsen Indeed :+1: 

ping @ruflin

**Comment by ruflin** [comment]
@nickygerritsen Could you put a note in the CHANGELOG.md file?

**Comment by nickygerritsen** [comment]
Done!

**Comment by ruflin** [comment]
@nickygerritsen Thanks for the fix
@nickygerritsen @ewgRa Do we need some follow up PR's to fix more stuff?

**Comment by ewgRa** [comment]
@ruflin I don't think so, it was kind of typo, and fully fixed and covered by test now.

**Comment by Tobion** [comment]
@ruflin can you make a patch release as this bug could affect many people?

**Comment by ruflin** [comment]
@Tobion Yes, that is possible. Put it on my TODO list for next week. Hope that works.

**Comment by mweibel** [comment]
@ruflin +1 on the patch release. Affects us right now :) Thanks! 👍

**Comment by ruflin** [comment]
Here you go: https://github.com/ruflin/Elastica/releases/tag/5.2.1

**Comment by mweibel** [comment]
Thanks! I noticed 5.2.1 has a BC break if you override `Elastica\Client::request()`

see: https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1258

**Comment by ruflin** [comment]
Oh, good point :-( Should we add this to the CHANGELOG? Thanks for fixing it in the bundle.

**Pull request merged**
