### PR TITLE
Added transport to support egeloen/http-adapter

### PR DESCRIPTION
**Pull request by agallou**
Supporting [egeloen/http-adapter](https://github.com/egeloen/ivory-http-adapter) will
allow to make http calls using  multiple libraries (including Guzzle3) :
- Buzz
- Cake
- cURL
- FileGetContents
- Fopen
- Guzzle
- GuzzleHttp
- Httpful
- React
- Socket
- Zend1
- Zend2

Here is an example of how to use it :

``` php
  $guzzle3 = new \Guzzle\Http\Client();

  $httpAdapter = new \Ivory\HttpAdapter\GuzzleHttpAdapter();
  $httpAdapterTransport = new \Elastica\Transport\HttpAdapter(null, $httpAdapter);

  $elastica = new \Elastica\Client(array(
      'connections' => array(
          array(
          '   host' => 'localhost',
              'port' => 9200,
              'transport' => $httpAdapterTransport,
          )
      )
  ));

  var_dump($elastica->getIndex('livre')->getType('livre')->getDocument('9782212136777')->getData());
```

### CODE REVIEW

**Comment by nurikabe** [comment]
Nice, though note that this relies on v0.6 of egeloen/http-adapter

**Comment by ruflin** [comment]
@nurikabe Does this mean it doesn't work with the never versions?

**Comment by agallou** [comment]
@ruflin I haven't tested it on newer versions, but PSR-7 is still in review (https://github.com/php-fig/fig-standards/blob/master/proposed/http-message-meta.md). 
When it will be accepted, I'll make a PR to made the changes if needed (I suppose that egeloen/http-adapter will adjust to use the standard interface).

**Comment by nurikabe** [comment]
Looks like another couple of weeks for PSR-7.  Hopefully it will go through this time.

I didn't dig very deep, but the initial problem I noticed was that `Ivory\HttpAdapter\Message\Stream\StringStream` has been replaced with https://github.com/phly/http

**Comment by ruflin** [comment]
Ok, lets wait for PSR-7 then.

**Comment by nurikabe** [comment]
PSR-7 approved last week on May 5th.

**Comment by ruflin** [comment]
@nurikabe Thanks for the update. 
@agallou Time for a Pull request? :-)

**Comment by agallou** [comment]
@ruflin tomorow is a public holiday, so I'll have a PR by the end of tomorow

**Comment by ruflin** [comment]
:+1:

**Pull request merged**
