### PR TITLE
PHP7 Compatibility: Rename Bool to BoolQuery and BoolFilter

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by stof** [comment]
There is one missing part: the BC layer with the old class names

**Comment by ruflin** [comment]
Jep, working on this one. I want to first check if it builds with renamed classes as my PHP 7 setup is not ready yet.

**Comment by stof** [comment]
@ruflin you should change the Travis config to trigger builds only for the master branch and PRs targetting the master branch. This would avoid having 2 builds being triggered for your own PRs, once for the PR and once for the branch push.
Given that Travis limits the number of concurrent jobs per repo owner (i.e. among all your repos) and that each build requires 12 jobs currently (ES_COMPOSER_NODEV being true or false for 6 different PHP versions), this would make the feedback faster on Travis (you currently have 16 builds in the Travis queue, with only one of them being running because of the restriction)

**Comment by stof** [comment]
btw, you might want to cancel builds for PRs which have been updated after that, keeping only the latest build for each PR to make the queue smaller

**Comment by ruflin** [comment]
@sten Jep. I already canceled most of the builds. It worked in the past as there were less jobs and it seems like travis gets more and more busy for open source projects: https://www.traviscistatus.com/ I'm also working on making the builds less heavy, especially the setup.

**Comment by stof** [comment]
@ruflin is it really needed to run both values of ES_COMPOSER_NODEV for each PHP version ?

**Comment by ruflin** [comment]
@stof There were some differences in the past where this was needed (and we had less PHP versions). But I will also look into this during checking for build process improvements.

**Comment by ruflin** [comment]
Seems like there are some issue with phpunit and PHP 7. Not sure what causes the segmentation fault: https://travis-ci.org/ruflin/Elastica/builds/62187485 To debug it I must setup my local PHP 7 version.

**Comment by stof** [comment]
@ruflin I suggest changing the coveralls config to report the status through the github PR status instead. Getting email notifications each time they build it is annoying (especially when they tell us they don't know what they should say)

**Comment by ruflin** [comment]
@stof I disabled comments for the moment. What I like about the comments is that it shows the coverage and the coverage changes. I'm testing codecov at the moment as there seem to be some issues with coveralls. https://github.com/ruflin/Elastica/pull/850

**Pull request merged**
