### PR TITLE
Bump query builder version to 7.0

### PR DESCRIPTION
**Pull request by deguif**
Follow-up of #1691

### CODE REVIEW

**Comment by deguif** [comment]
That's because there was a new version for PHP-CS-FIXER ;)

**Comment by deguif** [comment]
@ruflin once #1695 gets merged, I will rebase and the tests should be green

**Comment by ruflin** [comment]
Hm, interesting. I would hope such changes would not break our CI. What we should probably do moving forward is have a fixed version of the php-cs-fixer linked here instead of `^` .. https://github.com/ruflin/Elastica/blob/master/env/elastica/Lint#L36 ?

**Comment by deguif** [comment]
@ruflin rebased, and it's green now.

**Comment by ruflin** [comment]
Thanks, LGTM. Merged.

**Pull request merged**
