### PR TITLE
Migrate CI to github actions

### PR DESCRIPTION
**Pull request by deguif**

### CODE REVIEW

**Comment by deguif** [comment]
It wasn't much fun but that should work.
CI is broken on PHP 7.3 and 7.4 because of https://github.com/ruflin/Elastica/issues/1908 but @ezimuel is fixing it.

I think we should a add a conflict to avoid installing `elasticsearch/elasticsearch` 6.8.0 as it's broken.

**Comment by ezimuel** [comment]
I've the PR https://github.com/elastic/elasticsearch-php/pull/1114 for fixing 6.8.0.

**Comment by deguif** [comment]
Yes, thanks @ezimuel for that ;)

I've just added the conflict for specific version (`6.8.0`), this should allow to install `6.8.1` when it will be released, but disallow `6.8.0`.

**Comment by deguif** [comment]
@ruflin could you have a look.
I think we should release a `6.1.4` after merging this one to avoid the issue with `elasticsearch/elasticsearch` 6.8.0

**Review by ruflin — APPROVED** [review]
LGTM. Thanks for taking this on.

**Pull request merged**
