### PR TITLE
Add ignore_unavailable as a valid option to search

### PR DESCRIPTION
**Pull request by tmatei**
Could we add the ignore_unavailable option as a valid option to search?

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/multi-index.html#multi-index

### CODE REVIEW

**Comment by ruflin** [comment]
Sure. Can you add a small integration test here?

**Comment by tmatei** [comment]
Added tests, can you merge it?

**Comment by ruflin** [comment]
Ok merged it. Travis seems to have some issues at the moment :-(

**Comment by tmatei** [comment]
Thanks! I noticed unit tests take a very long time to run. Is this normal?

**Comment by ruflin** [comment]
It is not only unit tests, but also integration test. In total they should not take more then about 7 minutes (per environment). I also just merged https://github.com/ruflin/Elastica/pull/742 and hope with this the tests work again.

**Pull request merged**
