### PR TITLE
php-cs-fixer PreIncrementFixer

### PR DESCRIPTION
**Pull request by webdevsHub**
some housekeeping:

php-cs-fixer recently added PreIncrementFixer in [1.9](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v1.9) to `symfony` level. See also the [discussion](https://github.com/symfony/symfony/pull/14121).

### CODE REVIEW

**Comment by ruflin** [comment]
@webdevsHub If it is in 1.9 also the php-cs-fixer dependencies should be updated: https://github.com/ruflin/Elastica/blob/master/Dockerfile#L40

**Comment by webdevsHub** [comment]
Okay, I am going to do this before merge

**Comment by webdevsHub** [comment]
I modified `Dockerfile` to `RUN composer global require "fabpot/php-cs-fixer=1.10.*"`
but `make run RUN="make lint"` do not touch the files.

I downloaded it manually and `php php-cs-fixer.phar fix --config-file=./.php_cs` (with 1.10) changes one file `lib/Elastica/Aggregation/ReverseNested.php`. I am not into docker, but seems like I have to rebuild it or something?

**Comment by ruflin** [comment]
Yes, the image has to be rebuilt. The problem is, that by default it takes the remote image. As soon as we merge the pull request, it will build the new image. In the docker compose file a line is commented out. If you switch the comment, it will build it locally.

I suggest you push it here and we merge it. There is nothing major that can break ;-)

**Comment by webdevsHub** [comment]
that worked thx! Should be ready to merge

**Comment by ruflin** [comment]
Merged. Thx.

**Comment by ruflin** [comment]
@webdevsHub Here you can see that it just created the newest build for the latest push: https://registry.hub.docker.com/u/ruflin/elasticsearch-elastica/builds_history/205891/

**Pull request merged**
