### PR TITLE
Add Bucket sort aggregation

### LINKED ISSUE #2228: Missing Bucket Sort Aggregation
The Bucket Sort Aggregation is missing.
Elastic Search documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html

see #1787

### PR DESCRIPTION
**Pull request by gaetan-petit**
I tried to stick to existing code organization as much as possible.
The tests are very minimal.

Fixes #2228

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for the contribution. Could you add an entry to the changelog file?

Overall change LGTM. Glad to see the addition of the functional test to ensure it works. 

There is a test failure in one of the builds but I will run it again as I'm not sure how this could be related:

```
There was 1 failure:

1) Elastica\Test\PipelineTest::testDeletePipeline
an exception should be raised!

/home/runner/work/Elastica/Elastica/tests/PipelineTest.php:142
```

**Comment by ruflin** [comment]
All green now. Change LGTM. Can you add a commit with a changelog entry so we can get this in?

**Comment by gaetan-petit** [comment]
> All green now. Change LGTM. Can you add a commit with a changelog entry so we can get this in?

Sure I'll do it tomorrow! Thank you @ruflin

**Comment by gaetan-petit** [comment]
@ruflin done!
Now that I'm thinking I opened this PR against 8.x, are you going to publish any new release for the 7.x branch?

**Comment by ruflin** [comment]
Thx for opening it against 8.x, I rather have backports then forward ports. For the 7.x release: It depends if there are changes worth releasing. I will not make any promises but I would still recommend to backport it to 7.x. If you need a release there with this, please let me know ;-)

I'm waiting now in CI, as soon as all passes I'll get it merged.

**Comment by ruflin** [comment]
Thank you for the contribution! Looking forward to the 7.x backport ;-)

**Pull request merged**
