### PR TITLE
Add Query type, exists

### PR DESCRIPTION
**Pull request by EliuFlorez**

### CODE REVIEW

**Comment by p365labs** [comment]
@EliuFlorez please be a bit more declarative in PR's... give us some context in order to understand what u want to achieve

**Comment by ruflin** [comment]
@EliuFlorez Thanks for the contribution. Could you also update the changelog and add some tests?

**Comment by thePanz** [comment]
@EliuFlorez can you add a note about the `Type` query?
That query is deprecated in ES-7.0, from the latest docs:

> Deprecated in 7.0.0.
> Types and the type query are deprecated and in the process of being removed. See Removal of mapping types.)

**Comment by deguif** [comment]
Closing as `3.x` branch is not maintained anymore.
`exists` was added to query DSL in the mean time.

**Pull request closed without merging**
