### PR TITLE
add geo_bound aggregation

### PR DESCRIPTION
**Pull request by cobak78**
add geo_bound aggregation feature issued on https://github.com/ruflin/Elastica/issues/1270

### CODE REVIEW

**Comment by ruflin** [comment]
@cobak78 Could you update the changelog?

**Comment by ruflin** [comment]
@cobak78 Merged. Thanks for the contribution.

**Comment by Tobion** [comment]
The test file is now in the wrong place.

**Comment by ruflin** [comment]
:-( Missed that one. @cobak78 Could you open a follow up pr?

**Comment by Tobion** [comment]
#1272

**Comment by cobak78** [comment]
so, it's fixed on #1272?

**Comment by ruflin** [comment]
@cobak78 Correct.

**Pull request merged**
