### PR TITLE
Added geo_distance query builder method

### PR DESCRIPTION
**Pull request by arkadiuszmalina**

### CODE REVIEW

**Comment by filipgolonka** [comment]
:+1:

**Comment by wsromek** [comment]
👍

**Comment by bartosz-kahl** [comment]
👍

**Comment by ruflin** [comment]
Could you update the CHANGELOG.md file with these changes? It would also be nice to have at least 1 integration tests for each with elasticsearch to make sure it works as expected.

3 👍  in an hour, not bad ;-)

**Comment by rafalkanski** [comment]
👍

**Comment by ruflin** [comment]
@arkadiuszmalina Sorry, little bit late. But one thing I just realised is that AndQuery and OrQuery area already deprecated in elasticesarch 2.0 and will be removed in elasticsearch 5.0. It is replaced by the bool query: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-and-query.html

Are there some limitations you have with the existing Bool query?

**Comment by arkadiuszmalina** [comment]
@ruflin You're right, I cant belive I didn't notice it. I've change this PR to add only `geo_distance` method to query builder

**Comment by ruflin** [comment]
@arkadiuszmalina Merged. Thanks a lot for the contribution.

**Pull request merged**
