### PR TITLE
PHP 7.3 is EOL

### PR DESCRIPTION
**Pull request by frederikbosch**

### CODE REVIEW

**Comment by ruflin** [comment]
Change LGTM. Can you add an entry in the changelog file?

**Comment by deguif** [comment]
This package should be dropped when PHP version in requirements is at least 7.3 or greater, currently it's still `7.2`.
Would you mind updating the requirements too and drop tests configuration accordingly?

**Comment by frederikbosch** [comment]
Maybe drop every EOL version?

**Comment by sidz** [comment]
Looks like this PR can be closed. as we merged https://github.com/ruflin/Elastica/pull/2131

**Pull request closed without merging**
