### PR TITLE
Enable the support of "http.compression: true" in elasticsearch

### PR DESCRIPTION
**Pull request by yvann**
Hi !

After some tests and the reading of https://github.com/ruflin/Elastica/issues/515
I figured out that compress the request and the response can be a big performance improvement !
I don't know exactly where you want to put the configuration to enable this compression but here are the lines that works.

Hope it will help you !

### CODE REVIEW

**Comment by killerwolf** [comment]
+1

**Comment by ruflin** [comment]
@yvann Would you suggest to have it enabled as default? Best would to have config option for the connection which is probably called "compression". Check this line here: https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Client.php#L34

**Comment by ruflin** [comment]
BTW: Can you also update the CHANGELOG.md?

**Comment by yvann** [comment]
Let me do that, I come back in a minute :)

**Comment by ruflin** [comment]
Thx, merged.

**Comment by yvann** [comment]
Do you consider a version 2.2.2 with this merge ? Thanks

**Comment by ruflin** [comment]
Why not :-) But it would be 2.3.0 because of https://github.com/ruflin/Elastica/pull/916

**Comment by lenybernard** [comment]
Thanks, it looks good !
However, this is breaking things when a connection is given, it doesn't call the getConfig and then the compression param is not set correctly.
For the symfony guys who are using https://github.com/FriendsOfSymfony/FOSElasticaBundle, I made the PR https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/932 to set the compression param by default and avoid to crash.

2 notices, It should be interesting to up the version and it should be cool to have a readme to have more details about the request compression effects. 

Thank you !

**Comment by ruflin** [comment]
@lenybernard Thanks for bringing this up.
@yvann Can you have a look at this. I also just realised that the $compress config is at the wrong place. It should be noted as part of the $connections array here: https://github.com/yvann/Elastica/blob/11ec208cec201c8297570c2cdfe83608f0c713fb/lib/Elastica/Client.php#L34 If you want to set it as a global option, it must be fetched from the client. I suggest to add some tests to verify this.

**Pull request merged**
