### PR TITLE
Add avg_bucket & sum_bucket to aggregations

### PR DESCRIPTION
**Pull request by josselinh**

### CODE REVIEW

**Comment by josselinh** [comment]
Hello @ruflin ,

I can't get through the tests.
I don't understand what's wrong.
The tests were passed correctly for branch 5. x

Could you help me ?

**Comment by ruflin** [comment]
I assume there was a breaking change here in 6.x. I couldn't spot it on the first look. Can you check if you find something in the breaking changes for elasticsearch?

BTW: I'm glad we have the functional tests to discover this :-)

**Comment by josselinh** [comment]
Hello @ruflin ,
I finally found the error.
In ES v5, we can put spaces in buckets_path (ex: pages > sum_likes), but not in v6.

I'm going to make you a new PR for the branch 5.x to fix this so they'll be same

**Comment by ruflin** [comment]
@josselinh Thanks a lot for this change especially having it in both branches. You can ignore my comment in the other PR now :-)

**Comment by josselinh** [comment]
Thank you too.
Elastica is really great :)

**Pull request merged**
