### PR TITLE
Test v5 on PHP 7.3

### PR DESCRIPTION
**Pull request by jdreesen**
Test the v5 branch on PHP 7.3 too.

### CODE REVIEW

**Comment by p365labs** [comment]
@jdreesen can u please update the changelog?

**Comment by jdreesen** [comment]
The build failure on PHP 7.0 is unrelated.

**Comment by jdreesen** [comment]
Seems it was just a hiccup on travis.

**Comment by p365labs** [comment]
ops... conflict. need to rebase

**Comment by jdreesen** [comment]
Rebased.

**Pull request merged**
