### PR TITLE
Add no_useless_else and ternary_to_null_coalescing to PHPCs

### PR DESCRIPTION
**Pull request by carusogabriel**
Forgot to add them in #1421 and #1425 :sweat_smile:

### CODE REVIEW

**Comment by ruflin** [comment]
Change LGTM. There seems to be an issue with our travis builds at the moment not related to this :-(

Did you run `make lint` locally and there are 0 diffs at the moment?

**Comment by ruflin** [comment]
@carusogabriel Could you rebase on top of master? I just merged https://github.com/ruflin/Elastica/pull/1431

**Comment by carusogabriel** [comment]
I've rebased. Now I'm trying to run PHP-CS-Fixes locally

**Comment by ruflin** [comment]
Yeah, if you haven't setup docker yet, it will make your life harder, even though this was intended to make it easier for people to run to not have to install the libs etc. I will run it locally to see what the output will be.

BTW: You can also run the command outside of docker if you have all the dependencies installed.

**Comment by ruflin** [comment]
Merged it as there are only 2 very small diffs not related to this PR.

**Pull request merged**
